// <auto-generated />
using System;
using JemakEadPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JemakEadPro.Migrations
{
    [DbContext(typeof(JemakEadProContext))]
    [Migration("20221206162724_CriandoUsuario")]
    partial class CriandoUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JemakEadPro.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnName("Bairro")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("CEP")
                        .HasColumnName("CEP")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("CPF")
                        .HasColumnName("CPF")
                        .HasColumnType("VARCHAR(11)");

                    b.Property<string>("CarteiraProfissional")
                        .HasColumnName("CarteiraProficional")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Celular")
                        .HasColumnName("Celular")
                        .HasColumnType("VARCHAR(13)");

                    b.Property<string>("Cidade")
                        .HasColumnName("Cidade")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Complemento")
                        .HasColumnName("Complemento")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("CpfCnpj")
                        .HasColumnName("CpfCnpj")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("DataNascimento")
                        .HasColumnType("DateTime");

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Endereco")
                        .HasColumnName("Endereco")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Estado")
                        .HasColumnName("Estado")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("NomeResponsavel")
                        .HasColumnName("NomeResponsavel")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Numero")
                        .HasColumnName("Numero")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Perfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Perfil")
                        .HasColumnType("VARCHAR(100)")
                        .HasDefaultValue("usuario");

                    b.Property<string>("RG")
                        .HasColumnName("RG")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("ResponsavelTelefone")
                        .HasColumnName("ResponsavelTelefone")
                        .HasColumnType("VARCHAR(12)");

                    b.Property<string>("Senha")
                        .HasColumnName("Senha")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Sexo")
                        .HasColumnName("Sexo")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Telefone")
                        .HasColumnName("Telefone")
                        .HasColumnType("VARCHAR(13)");

                    b.Property<string>("TelefoneTrabalho")
                        .HasColumnName("TelefoneTrabalho")
                        .HasColumnType("VARCHAR(13)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasName("IX_Usuario_CPF");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("IX_Usuario_Email");

                    b.HasIndex("Nome")
                        .HasName("Ix_Usuario_Nome");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
